# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json





site_name: ALU on Digital Logical Sim
#site_url: https://mydomain.org/mysite
repo_url: https://github.com/nnpfr/alu

docs_dir: documentation

theme:
  name: material
  palette:
    - scheme: default
      primary: light blue
      accent: deep purple
      toggle:
        icon: material/brightness-4
        name: Passer en mode sombre
    - scheme: slate
      primary: indigo
      accent: amber
      toggle:
        icon: material/brightness-7
        name: Passer en mode clair


  features:
    - navigation.instant

nav:
  - Welcome: index.md
  - Introduction:
    - "Installing and FAQ": introduction/FAQ.md
    - "Logic gates": introduction/logic_gates.md
    - "Table of the chips": introduction/chips.md


markdown_extensions:
  - pymdownx.tasklist
  - footnotes
  - markdown.extensions.extra
